#!/usr/bin/env `(if (equal (file-name-extension buffer-file-name) "zsh") "zsh" "bash")`
# -*- time-stamp-pattern: "changed[\s]+:[\s]+%%$"; -*-
# AUTHOR INFORMATION ###########################################################
# file    : `(file-name-nondirectory (buffer-file-name))`
# author  : ${1:`user-full-name` <`user-mail-address`>}
#
# created : `(format-time-string "%04Y-%02m-%02d %02H:%02M:%02S")` (`(user-full-name)`)
# changed : 2021-01-20 08:37:41 (Marcel Arpogaus)
# DESCRIPTION ##################################################################
# ...
# LICENSE ######################################################################
# ...
################################################################################
$2